// AUDIT_ROUND_16 — Mock trials. Five realistic defense-counsel attacks on
// petitions generated by the filing generator. Each mock trial:
//
//   1. Seeds a fact pattern that a real defendant would run into court,
//   2. Runs generateFilingPackage against it,
//   3. Applies a motion the defendant's counsel would file (MTD 12(b)(1)
//      standing, motion in limine on hearsay, motion to dismiss Count II
//      for failure to plead ATDS under Duguid, etc.),
//   4. Grades the petition's response language against what it would
//      need to say to survive that motion.
//
// This is deliberately harsher than the pressure tests — those were
// bug hunts ("can I break the generator"), these are legal-sufficiency
// checks ("will this filing survive defense counsel's first motion").
//
// Run:  cd backend && npx ts-node _audit16_mock_trials.ts

import * as CaseBuilder from "./src/services/caseBuilder";
import { generateFilingPackage } from "./src/services/legalFilingGenerator";
import fs from "fs";
import path from "path";

const CASES_PATH = path.resolve(__dirname, "..", "cases.json");
const PHONE_PATH = path.resolve(__dirname, "..", "phone.json");

interface TrialResult {
  id: string;
  title: string;
  motion: string;
  survived: boolean;
  notes: string[];
}
const results: TrialResult[] = [];
function record(r: TrialResult) {
  results.push(r);
  const flag = r.survived ? "✓ SURVIVED" : "✗ LOST";
  console.log(`  ${flag}  ${r.id}: ${r.title}`);
  console.log(`      motion: ${r.motion}`);
  for (const n of r.notes) console.log(`        - ${n}`);
}

// ── Seeding helper (copied from pressure tests) ─────────────────────────
function seedOffender(opts: {
  phone: string;
  companyName: string | null;
  callerName: string | null;
  purpose: string | null;
  numCalls: number;
  oldestCallDaysAgo: number;
  hasRecording?: boolean;
  callType?: string;
}): string {
  const key = CaseBuilder.normalizePhone(opts.phone);
  const calls: any[] = [];
  for (let i = 0; i < opts.numCalls; i++) {
    const span = Math.max(1, opts.oldestCallDaysAgo - 1);
    const daysAgo = opts.numCalls === 1
      ? opts.oldestCallDaysAgo
      : opts.oldestCallDaysAgo - Math.floor((i / (opts.numCalls - 1)) * span);
    const ts = new Date(Date.now() - daysAgo * 86400 * 1000);
    calls.push({
      date: ts.toISOString().split("T")[0],
      time: ts.toTimeString().slice(0, 5),
      callSid: `CA_MOCK_${i}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
      subscriberId: "test",
      recordingUrl: opts.hasRecording ? `https://api.twilio.com/recordings/mock_${i}` : null,
      transcriptSnippet: `Hi, we're calling about your car's extended warranty. This call may be recorded.`,
      callType: opts.callType ?? "robocall",
    });
  }
  calls.sort((a, b) => (a.date + a.time).localeCompare(b.date + b.time));
  const profile = {
    normalizedNumber: key,
    rawNumbers: [opts.phone],
    companyName: opts.companyName,
    callerNames: opts.callerName ? [opts.callerName] : [],
    purpose: opts.purpose,
    callCount: opts.numCalls,
    calls,
    firstCallDate: calls[0].date,
    lastCallDate: calls[calls.length - 1].date,
    actionable: opts.numCalls >= 2,
    willful: false,
    damagesEstimate: opts.numCalls * 500,
    demandLetterSent: false,
    demandLetterDate: null,
    subscriberIds: ["test"],
    filedAt: null,
    filedCaseRef: null,
  };
  const db = JSON.parse(fs.readFileSync(CASES_PATH, "utf-8"));
  db[key] = profile;
  fs.writeFileSync(CASES_PATH, JSON.stringify(db, null, 2));
  return key;
}
function cleanupOffender(key: string) {
  try {
    const db = JSON.parse(fs.readFileSync(CASES_PATH, "utf-8"));
    delete db[key];
    delete db[`${key}#post-filed`];
    fs.writeFileSync(CASES_PATH, JSON.stringify(db, null, 2));
  } catch {}
}

// ── phone.json harness ────────────────────────────────────────────────────
let originalPhoneJson: string | null = null;
try { originalPhoneJson = fs.readFileSync(PHONE_PATH, "utf-8"); } catch {}
const baseFilingConfig = {
  userName: "Jane Plaintiff",
  userAddress: "456 Test Lane",
  userCity: "Lafayette",
  userState: "LA",
  userZip: "70501",
  userPhone: "+13375551234",
  userEmail: "jane@example.com",
  courtName: "Lafayette City Court",
  courtAddress: "800 S. Buchanan Street",
  courtCity: "Lafayette",
  courtState: "LA",
  courtZip: "70501",
  courtClerkPhone: "(337) 291-8760",
  parishOrCounty: "Lafayette Parish",
  dncRegistrationDate: "2015-06-01",
  filingFee: "$75.00",
  serviceFee: "$25.00",
  stateDncStatute: "La. R.S. 45:844.14",
  stateRecordingLaw: "La. R.S. 15:1303 (one-party consent)",
  smallClaimsLimit: "$5,000",
  smallClaimsStatute: "La. R.S. 13:5200 et seq.",
  lineType: "residential",
};
function writePhoneJson(overrides: Partial<typeof baseFilingConfig> = {}) {
  const base = originalPhoneJson ? JSON.parse(originalPhoneJson) : {};
  base.filingConfig = { ...baseFilingConfig, ...overrides };
  fs.writeFileSync(PHONE_PATH, JSON.stringify(base, null, 2));
}
function restorePhoneJson() {
  if (originalPhoneJson !== null) fs.writeFileSync(PHONE_PATH, originalPhoneJson);
}

// ── Run the 5 mock trials ────────────────────────────────────────────────

console.log("\n═══ AUDIT_ROUND_16 — 5 MOCK TRIALS ═══\n");
const keys: string[] = [];

// ─────────────────────────────────────────────────────────────────────────
//  MT1 — Rule 12(b)(1) standing: defendant moves to dismiss for lack of
//        Article III standing, arguing TransUnion requires "concrete harm"
//        and a robocall answered by an automated system is not concrete.
// ─────────────────────────────────────────────────────────────────────────
try {
  writePhoneJson();
  const k = seedOffender({
    phone: "+15551110001",
    companyName: "Coastal Telemarketing LLC",
    callerName: "Agent",
    purpose: "extended auto warranty",
    numCalls: 4,
    oldestCallDaysAgo: 90,
    hasRecording: true,
  });
  keys.push(k);
  const pkg = generateFilingPackage(k);
  const petition = pkg?.petition ?? "";
  const notes: string[] = [];
  let survived = !!pkg;

  // Required elements to beat a TransUnion standing challenge:
  const needs = [
    { re: /TransUnion\s+LLC\s+v\.?\s+Ramirez/i,     why: "must cite TransUnion v. Ramirez (2021)" },
    { re: /Spokeo[^\n]*?v\.?\s+Robins/i,             why: "must cite Spokeo v. Robins (2016)" },
    { re: /close\s+relationship/i,                   why: "must articulate TransUnion 'close relationship' test" },
    { re: /intrusion\s+upon\s+seclusion/i,           why: "must map harm to a traditionally recognized common-law tort" },
    { re: /trespass\s+to\s+chattels/i,               why: "must alternatively ground harm in trespass to chattels" },
    { re: /regardless\s+of\s+(?:the\s+)?answering\s+mechanism|not\s+to\s+whichever\s+device/i,
                                                     why: "must rebut 'but a bot answered' argument head-on" },
    { re: /concrete\s+and\s+particularized/i,        why: "must use Lujan/Spokeo magic words 'concrete and particularized'" },
  ];
  for (const n of needs) {
    if (!n.re.test(petition)) { survived = false; notes.push(`MISSING: ${n.why}`); }
  }
  if (survived) notes.push("All 7 TransUnion-defeating elements present and on-point.");
  record({
    id: "MT1",
    title: "Article III standing — 'bot answered, no concrete harm'",
    motion: "Rule 12(b)(1) motion to dismiss for lack of Article III standing",
    survived,
    notes,
  });
} catch (e) {
  record({ id: "MT1", title: "Article III standing", motion: "12(b)(1)", survived: false, notes: [`threw: ${(e as Error).message.slice(0, 200)}`] });
}

// ─────────────────────────────────────────────────────────────────────────
//  MT2 — Duguid ATDS narrowing: cellular-line plaintiff. Defense MTD on
//        Count II arguing § 227(b)(1)(A)(iii) requires ATDS, and after
//        Facebook v. Duguid (2021) a prerecorded message on a non-random
//        number list doesn't qualify — must separately plead prerecorded
//        voice or drop the ATDS theory.
// ─────────────────────────────────────────────────────────────────────────
try {
  writePhoneJson({ lineType: "cellular" });
  const k = seedOffender({
    phone: "+15551110002",
    companyName: "Solar Scams Inc",
    callerName: "Bob",
    purpose: "solar panel installation",
    numCalls: 5,
    oldestCallDaysAgo: 120,
    hasRecording: true,
  });
  keys.push(k);
  const pkg = generateFilingPackage(k);
  const petition = pkg?.petition ?? "";
  const notes: string[] = [];
  let survived = !!pkg;

  const needs = [
    { re: /Facebook,?\s+Inc\.?\s+v\.?\s+Duguid/i,    why: "must cite Facebook v. Duguid (2021) by name" },
    { re: /random\s+or\s+sequential\s+number\s+generator/i,
                                                     why: "must recite Duguid's ATDS definition verbatim" },
    { re: /artificial\s+or\s+prerecorded\s+voice/i,  why: "must plead the alternative prerecorded-voice theory" },
    { re: /227\(b\)\(1\)\(A\)\(iii\)/,               why: "must cite § 227(b)(1)(A)(iii) for cellular" },
    // The petition should NOT commit the plaintiff to a definitive ATDS
    // claim — it should plead ATDS on "information and belief" so the
    // defense can't win on a missing element. Check for hedging language.
    { re: /information\s+and\s+belief/i,             why: "ATDS allegation must be pled on information and belief (Duguid makes proof hard pre-discovery)" },
  ];
  for (const n of needs) {
    if (!n.re.test(petition)) { survived = false; notes.push(`MISSING: ${n.why}`); }
  }
  // Anti-requirement: petition must NOT swear categorically that
  // Defendant used an ATDS — that's a Rule 11 / Duguid trap.
  if (/Defendant\s+used\s+an\s+ATDS[.,]/i.test(petition) &&
      !/information\s+and\s+belief/i.test(petition)) {
    survived = false;
    notes.push("OVERCOMMIT: categorical 'Defendant used an ATDS' without 'information and belief' hedge");
  }
  if (survived) notes.push("Petition navigates Duguid narrowing without overcommitting.");
  record({
    id: "MT2",
    title: "Duguid ATDS narrowing — cellular line",
    motion: "Rule 12(b)(6) partial MTD on § 227(b)(1)(A)(iii) ATDS count",
    survived,
    notes,
  });
} catch (e) {
  record({ id: "MT2", title: "Duguid ATDS narrowing", motion: "12(b)(6)", survived: false, notes: [`threw: ${(e as Error).message.slice(0, 200)}`] });
}

// ─────────────────────────────────────────────────────────────────────────
//  MT3 — Prior express consent / EBR affirmative defense: defendant answer
//        raises "plaintiff filled out a lead form two years ago" and "EBR
//        was established." Does the petition PREEMPT these defenses so a
//        boilerplate answer doesn't create a triable factual dispute?
// ─────────────────────────────────────────────────────────────────────────
try {
  writePhoneJson();
  const k = seedOffender({
    phone: "+15551110003",
    companyName: "LeadVendor LLC",
    callerName: "Caller",
    purpose: "home improvement quote",
    numCalls: 3,
    oldestCallDaysAgo: 60,
    hasRecording: true,
  });
  keys.push(k);
  const pkg = generateFilingPackage(k);
  const petition = pkg?.petition ?? "";
  const notes: string[] = [];
  let survived = !!pkg;

  const needs = [
    // Consent rebuttal
    { re: /no\s+knowledge\s+or\s+record\s+of\s+ever\s+providing|after\s+reasonable\s+inquiry/i,
                                                     why: "must softly deny consent 'after reasonable inquiry' (AUDIT_ROUND_15 H3)" },
    { re: /prior\s+express\s+(?:written\s+)?consent/i, why: "must name the 'prior express consent' standard" },
    // EBR rebuttal
    { re: /established\s+business\s+relationship|EBR/i, why: "must affirmatively plead no EBR" },
    { re: /64\.1200\(f\)\(5\)/,                      why: "must cite the EBR regulation 47 C.F.R. § 64.1200(f)(5)" },
    { re: /18\s+months/i,                            why: "must quote the 18-month EBR look-back window" },
    // Entrapment / unclean hands preemption
    { re: /entrapment|unclean\s+hands/i,             why: "must preempt entrapment/unclean-hands defenses from recording" },
  ];
  for (const n of needs) {
    if (!n.re.test(petition)) { survived = false; notes.push(`MISSING: ${n.why}`); }
  }
  if (survived) notes.push("Consent/EBR/entrapment defenses all pre-empted in the chief pleading.");
  record({
    id: "MT3",
    title: "Prior express consent + EBR affirmative defenses",
    motion: "Answer raises prior consent + EBR as affirmative defenses",
    survived,
    notes,
  });
} catch (e) {
  record({ id: "MT3", title: "Consent/EBR", motion: "Answer", survived: false, notes: [`threw: ${(e as Error).message.slice(0, 200)}`] });
}

// ─────────────────────────────────────────────────────────────────────────
//  MT4 — Residential primary-use contest: line is "unspecified" (user
//        didn't pick in Settings). Defense argues no § 227(c) residential
//        protection, petition must plead standing without swearing the
//        line is residential.
// ─────────────────────────────────────────────────────────────────────────
try {
  writePhoneJson({ lineType: "unspecified" });
  const k = seedOffender({
    phone: "+15551110004",
    companyName: "AmbigCorp",
    callerName: "Rep",
    purpose: "insurance",
    numCalls: 4,
    oldestCallDaysAgo: 45,
    hasRecording: true,
  });
  keys.push(k);
  const pkg = generateFilingPackage(k);
  const petition = pkg?.petition ?? "";
  const warnings = pkg?.warnings ?? [];
  const notes: string[] = [];
  let survived = !!pkg;

  // MUST have loud warning so the filer knows not to sign
  if (!warnings.some((w) => /LINE\s+TYPE\s+NOT\s+CONFIRMED/i.test(w))) {
    survived = false;
    notes.push("MISSING: 'LINE TYPE NOT CONFIRMED' warning in pkg.warnings");
  }
  // MUST NOT contain a sworn categorical "residential primary use" claim
  // when the user never selected residential.
  if (/use\s+the\s+number\s+primarily\s+for\s+residential(?!\s+or\s+personal\s+purposes\s+only\s+to\s+the\s+extent)/i.test(petition) &&
      !/to\s+the\s+extent\s+Plaintiff/i.test(petition)) {
    // Try both strict and loose match — the whole point is we DON'T want
    // a bare claim. If it's hedged with "to the extent", it's OK.
    const strictClaim = /Plaintiff\s+is\s+the\s+subscriber[^.]*primarily\s+for\s+residential/i;
    const hedged = /to\s+the\s+extent\s+Plaintiff'?s\s+line\s+qualifies\s+as\s+a\s+residential/i;
    if (strictClaim.test(petition) && !hedged.test(petition)) {
      survived = false;
      notes.push("OVERCLAIM: sworn 'primarily residential' language present without hedging despite lineType=unspecified");
    }
  }
  // MUST contain the hedged "to the extent" § 227(b)(1)(B) paragraph.
  if (!/to\s+the\s+extent\s+Plaintiff'?s\s+line\s+qualifies\s+as\s+a\s+residential/i.test(petition)) {
    survived = false;
    notes.push("MISSING: 'to the extent ... residential' hedged § 227(b)(1)(B) paragraph");
  }
  if (survived) notes.push("Filing package warns user AND hedges standing paragraphs appropriately.");
  record({
    id: "MT4",
    title: "Residential primary-use contest — lineType=unspecified",
    motion: "Rule 12(b)(6) MTD on § 227(c)(5) — 'line is not residential'",
    survived,
    notes,
  });
} catch (e) {
  record({ id: "MT4", title: "Primary-use contest", motion: "12(b)(6)", survived: false, notes: [`threw: ${(e as Error).message.slice(0, 200)}`] });
}

// ─────────────────────────────────────────────────────────────────────────
//  MT5 — Evidentiary attack: motion in limine to exclude recordings as
//        unauthenticated hearsay. Defense also challenges chain of custody
//        (recordings stored on third-party Twilio, plaintiff could have
//        altered them).
// ─────────────────────────────────────────────────────────────────────────
try {
  writePhoneJson();
  const k = seedOffender({
    phone: "+15551110005",
    companyName: "EvidenceCo",
    callerName: "Caller",
    purpose: "credit repair",
    numCalls: 4,
    oldestCallDaysAgo: 30,
    hasRecording: true,
  });
  keys.push(k);
  const pkg = generateFilingPackage(k);
  const petition = pkg?.petition ?? "";
  const exhibits = pkg?.exhibitList ?? "";
  const all = petition + "\n" + exhibits;
  const notes: string[] = [];
  let survived = !!pkg;

  const needs = [
    // Authentication
    { re: /SHA-?256/i,                               why: "must cite SHA-256 hash authentication" },
    { re: /cryptographic\s+hash(?:es)?/i,            why: "must explain cryptographic hashing in lay terms" },
    { re: /FIPS\s*180-?4|federal\s+standard/i,       why: "must invoke FIPS 180-4 to legitimize the hash method" },
    { re: /Fed\.?\s*R\.?\s*Evid\.?\s*901|Rule\s+901|Art\.?\s+901|901\(a\)/i,
                                                     why: "must cite FRE/La. CE 901 for authentication" },
    // Chain of custody
    { re: /Twilio[^.]*?(?:third[- ]party|platform)/i,
                                                     why: "must frame Twilio as third-party custodian, not plaintiff-controlled" },
    { re: /(?:NYSE|publicly\s+traded)/i,             why: "must note Twilio is publicly traded (neutrality bolster)" },
    { re: /carrier\s+(?:Call\s+Detail|CDR)/i,        why: "must offer carrier CDR as independent corroboration" },
    { re: /Call\s+SID/i,                             why: "must expose Twilio Call SID for subpoena discoverability" },
    // Non-hearsay framing: caller statements are party-opponent admissions,
    // not hearsay at all. The petition doesn't currently cite FRE 801(d)(2)
    // explicitly — flag it as a finding so we can decide whether to add it.
    { re: /party[- ]opponent|801\(d\)\(2\)/i,        why: "SHOULD cite FRE 801(d)(2) / party-opponent admission to defeat hearsay pre-emptively" },
  ];
  for (const n of needs) {
    if (!n.re.test(all)) { survived = false; notes.push(`MISSING: ${n.why}`); }
  }
  if (survived) notes.push("Evidence-authentication package survives motion in limine.");
  record({
    id: "MT5",
    title: "Hearsay + chain-of-custody attack on recordings",
    motion: "Motion in limine to exclude recordings (FRE 901 authentication, FRE 802 hearsay)",
    survived,
    notes,
  });
} catch (e) {
  record({ id: "MT5", title: "Evidence attack", motion: "MIL", survived: false, notes: [`threw: ${(e as Error).message.slice(0, 200)}`] });
}

// ── Cleanup + summary ────────────────────────────────────────────────────
for (const k of keys) cleanupOffender(k);
restorePhoneJson();

console.log("\n═══ MOCK TRIAL SUMMARY ═══");
const lost = results.filter((r) => !r.survived);
console.log(`${results.length - lost.length}/${results.length} survived defense motions.\n`);
if (lost.length > 0) {
  console.log("LOSSES:");
  for (const r of lost) {
    console.log(`  ${r.id}: ${r.title}`);
    for (const n of r.notes.filter((x) => x.startsWith("MISSING") || x.startsWith("OVERCLAIM") || x.startsWith("OVERCOMMIT") || x.startsWith("threw"))) {
      console.log(`      → ${n}`);
    }
  }
}
process.exit(lost.length > 0 ? 1 : 0);
